bus/urls.py
from django.contrib import admin
from django.urls import include, path
from qrgenerator import views
from transaction import views


urlpatterns = [
 path('',include('auth_app.urls')),
 path('passenger/',include('passenger.urls',namespace='passenger')),
 path('passes',include('passes.urls',namespace='passes')),
path('transaction/',include('transaction.urls',namespace='transaction')),
 path('report',include('report.urls',namespace='reports')),
 path('search',include('search.urls',namespace='find'))


   

]   

passes/urls.py
from django.contrib import admin
from django.urls import include, path
from passenger import views
from passes import views  

app_name = 'passes'
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),  
    path('addnew/',views.addnew, name='addnew'),  
    path('edit/<int:id>', views.edit, name='edit'),  
    path('update/<int:id>', views.update, name='update'),  
    path('delete/<int:id>', views.destroy, name='destroy'),

]

passes/models.py
from django.db import models

class Passes(models.Model):  
    name = models.CharField(max_length=100)  
    city = models.CharField(max_length=100)
    passtype_choices = [
        ('Dailypass', 'Dailypass'),
        ('Monthlypass', 'Monthlypass'),
        ('Annualpass', 'Annualpass'),
        ('Differently abled pass', 'Differently Abled pass'),
        ('school pass', 'School pass'),
        ('College pass', 'college pass'),
    ]
    passtype = models.CharField(max_length=100, choices=passtype_choices)
    amount= models.CharField(max_length=100)
        
        
  
    class Meta:  
        db_table = "tblpases_1"

report/models.py
from django.db import models
import uuid

from django.db import models

class transaction(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=100)  
    city = models.CharField(max_length=100)
    fromdate = models.DateField()
    todate = models.DateField()
    trdate = models.DateField()
    fromplace = models.CharField(max_length=50)  # Fix the typo here
    toplace = models.CharField(max_length=50)    # Fix the typo here
    address = models.CharField(max_length=50)    # Fix the typo here
    amount = models.CharField(max_length=100)  
    contact = models.CharField(max_length=15)
    passtype_choices = [
        ('Dailypass', 'Dailypass'),
        ('Monthlypass', 'Monthlypass'),
        ('Annualpass', 'Annualpass'),
        ('Differently abled pass', 'Differently Abled pass'),
        ('school pass', 'School pass'),
        ('College pass', 'college pass'),
        # Add more options as needed
    ]
    passtype = models.CharField(max_length=100, choices=passtype_choices)

    def __str__(self):
            return str(self.uuid)
   
    


passes/forms.py
from django import forms

from passes.models import Passes 


class passesForm(forms.ModelForm):  
    class Meta:  
        model = Passes  
        fields = ['name','passtype','city','amount'] 
        widgets = { 'name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'city': forms.TextInput(attrs={ 'class': 'form-control' }),
            'passtype': forms.Select(attrs={'class': 'form-control'}), 
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
            
          
      }

passes/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect, render
from passes.forms import passesForm  
from passes.models import Passes

# Create your views here.
def addnew(request):  
    if request.method == "POST":  
        form = passesForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('passes:index')  
            except:  
                pass
    else:  
        form = passesForm()  
    return render(request,'passes/index.html',{'form':form})  
 
def index(request):  
    passes = Passes.objects.all()  
    return render(request,"passes/show.html",{'passes':passes})  
 
def edit(request, id):  
    passes = Passes.objects.get(id=id)  
    return render(request,'passes/edit.html', {'passes':passes})  
 
def update(request, id):  
    passes = Passes.objects.get(id=id)  
    form = passesForm(request.POST, instance = passes)  
    if form.is_valid():  
        form.save()  
        return redirect('/')  
    return render(request, 'passes/edit.html', {'passes': passes})  
     
def destroy(request, id):  
    passes = Passes.objects.get(id=id)  
    passes.delete()  
    return redirect('/')  

templates/passes/edit.html
{% extends "base.html" %}
  
{% block title %}Add New passes Records{% endblock title %}
  
{% block content %}
<div class="col-md-12">
           <form method="POST" class="post-form" action="{% url 'passes:update' passes.id %}"> 
            {% csrf_token %} 
            <div class="container">  
                    <div class="col-12"> 
                            <h3>Update Details</h3> 
                        </div>
                    <div class="mb-3">
                            <label>passes ID:</label> 
                            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
                    value="{{ passes.id }}" />   
                        </div>
                    <div class="mb-3">
                            <label>Name:</label> 
                            <input type="text" class="form-control" name="name" id="id_name" required maxlength="100"
                    value="{{ passes.name }}" /> 
                        </div>
                    <div class="mb-3">
                            <label>city:</label> 
                            <input type="text" class="form-control" name="city" id="id_email" required maxlength="254"
                    value="{{ passes.city }}" /> 
                        </div>
            <div class="mb-3">
                            <label>amount:</label> 
                            <input type="text" class="form-control" name="address" id="id_address" required
                    maxlength="20" value="{{ passes.amount }}" />   
                        </div>
                    <div class="mb-3">
                            <label>passtype:</label> 
                            <input type="text" class="form-control" name="contact" id="id_passtype" required
                    maxlength="15" value="{{ passes.passtype }}" /> 
                        </div>
                    <div class="mb-3">
                            <button type="submit" class="btn btn-success btn-lg">Update</button> 
                        </div>
                
        </div> 
            </form> 
    {% endblock content %}  

templates/passes/index.html
{% extends "base.html" %}
  
{% block title %}Add New passes Records{% endblock title %}

  
{% block content %}
<div class="col-md-12">   
        <form method="POST" class="post-form" action="{% url 'passes:addnew' %}"> 
            {% csrf_token %} 
            <div class="container"> 
                    <div class="col-12"> 
                        <h3>Enter Details</h3> 
                        </div>   
                 
                    <div class="mb-3">
                            <label>Name:</label> 
                            {{ form.name }}  
                        </div>
                    <div class="mb-3">
                            <label>city:</label> 
                            {{ form.city }}  
                        </div> 
             <div class="mb-3">
                            <label>amount:</label> 
                            {{ form.amount }}  
                        </div>
             <div class="mb-3">
                            <label>passtype:</label> 
                            {{ form.passtype }}  
                        </div>   
                    <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Submit</button>   
                        </div>
                </div> 
            </form> 
</div>

{% endblock content %}

templates/passes/show.html
{% extends "base.html" %}
  
{% block title %}Passes Records{% endblock title %}
  
{% block content %}
 <div class="col-md-12">
        <span><a href="{% url 'passes:addnew' %}" class="btn btn-primary">Add New Record</a></span>  
        <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th> Name</th>
            <th> city</th>
            <th> amount</th>
            <th>passes passtype</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for passes in passes %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ passes.id }}</td>  
            <td>{{ passes.name }}</td>  
            <td>{{ passes.city }}</td>
            <td>{{ passes.amount }}</td>  
            <td>{{ passes.passtype}}</td>     
             <td><a href="{% url 'passes:edit' id=passes.id %}" class="btn btn-primary">Edit</a></td>
            <td><a href="{% url 'passes:destroy' id=passes.id %}" class="btn btn-danger">Delete</a></td>  
            </tr>  
        {% endfor %} 
        </tbody>
        </table>
        </div>
    </div>
{% endblock content %}